### ISSUE TITLE
Maskmentor's code

### ISSUE THREAD

**Issue by jikedream** [Zhao-ZD/MaskMentor#2]
Hello, I **encountered some problems** with the implementation details when reproducing Maskmentor, such as whether the output tokens of the teacher model and the student model should be added with mask tokens and then passed through the cross attention module, or directly passed through the cross attention module without adding mask tokens and then adding mask tokens. 
  The model pictures and the paper content do not match. In addition, how to distill the teacher model and the student model, and what loss to use. I am looking forward to your code!
  Great work

**Comment by johndpope** [comment]
did you see this referenced paper MultiMAE  https://multimae.epfl.ch/ ?

this maybe the answer to teacher / student / loss training -https://github.com/skyoux/mokd/blob/f7b138618c6730d0aa61f0d3e183e62d11330763/models/mokd.py#L106

**Comment by jikedream** [comment]
> 你看到这篇参考论文 MultiMAE https://multimae.epfl.ch/了吗？
> 
> 这也许是教师/学生/损失训练的答案 - https://github.com/skyoux/mokd/blob/f7b138618c6730d0aa61f0d3e183e62d11330763/models/mokd.py#L106

I **referred to the code of this paper(multimae)**, but this maskmentor made some improvements based on this paper, so I am a little confused about the implementation of the specific details. 
**Thanks for your answer**

**Comment by jikedream** [comment]
> did you see this referenced paper MultiMAE https://multimae.epfl.ch/ ?
> 
> this maybe the answer to teacher / student / loss training -https://github.com/skyoux/mokd/blob/f7b138618c6730d0aa61f0d3e183e62d11330763/models/mokd.py#L106

I referred to the code of this paper(multimae), but this maskmentor made some improvements based on this paper, so I am a little confused about the implementation of the specific details.
Thanks for your answer
